name: Standalone Executable

on:
  push:
    branches:
    - executable
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build executable 📦 for windows
    runs-on: windows-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.11

      - name: Install development dependencies
        run: |
          python3 -m pip install -r requirements-exe.txt
          python3 setup.py build_ext -i
          python3 setup.py py2exe >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4.4.1
        with:
          name: standalone
          path: dist/*.exe
