name: Tests

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.ipynb'
      - '**/*.c'
      - '**/*.h'
      - '**/*.toml'
      - '.github/workflows/test-continuous.yml'  # run if this file is changed
      - '!docs/conf.py'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.codecov.io:443
            api.github.com:443
            cli.codecov.io:443
            codecov.io:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - name: Check out the commit
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install gcovr==5.0

      - name: Build test
        run: python3 -m pip install -e .[formats,examples,tests]

      - name: Get C++ coverage
        run: |
          export CPPFLAGS="-coverage"
          python3 setup.py build_ext --inplace --force
          echo '### Run tests' >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          python3 -m pytest --nbmake --disable-warnings --cov=sansmic --cov=tests --no-header --color=auto docs/examples/ tests/ | tee -a $GITHUB_STEP_SUMMARY
          find src -type f -name '*.cpp' | xargs -I{} gcov -o build/temp*/src/ext_modules/libsansmic {}
          echo ' ' >> $GITHUB_STEP_SUMMARY
          gcovr --txt -s -k | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage reports to Codecov
        continue-on-error: true
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Test uninstall
        # Allow upload to codecov to fail but not fail all tests
        run: python3 -m pip uninstall -y sansmic
